version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai-agents-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - ai-agents-dev-network

  # Interface web para monitorar o Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ai-agents-redis-commander-dev
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ai-agents-dev-network

volumes:
  redis_dev_data:
    driver: local

networks:
  ai-agents-dev-network:
    driver: bridge