"""
LLM-Enhanced Report Agent for generating intelligent executive reports with business insights
"""

import asyncio
import os
import json
from typing import Dict, Any, List, Optional
from enum import Enum
from datetime import datetime
import structlog

from .base_agent import BaseAgent
from utils.config import settings
from utils.openai_integration import get_openai_service, BusinessInsights, LLMResponse


class ReportFormat(Enum):
    """Supported report formats"""
    PDF = "pdf"
    XLSX = "xlsx"
    DOCX = "docx"


class ReportTemplate(Enum):
    """Available report templates"""
    EXECUTIVE_SUMMARY = "executive_summary"
    SUPPLIER_ANALYSIS = "supplier_analysis"
    PRODUCT_ANALYSIS = "product_analysis"
    TAX_ANALYSIS = "tax_analysis"
    MONTHLY_REPORT = "monthly_report"
    CUSTOM = "custom"


class IntelligentReport:
    """Enhanced report representation with LLM-generated insights"""
    
    def __init__(self, title: str, format: ReportFormat, template: ReportTemplate):
        self.title = title
        self.format = format
        self.template = template
        self.content = {}
        self.metadata = {}
        self.file_path = None
        self.created_at = datetime.now()
        self.size_bytes = 0
        # LLM-enhanced fields
        self.insights: Optional[BusinessInsights] = None
        self.executive_summary: Optional[Dict[str, Any]] = None
        self.recommendations: List[Dict[str, Any]] = []
        self.confidence_score: float = 0.0
        self.llm_processing_stats: Dict[str, Any] = {}

class ReportContext:
    """Context for intelligent report generation"""
    
    def __init__(self, business_objectives: List[str], audience: str = "executive", 
                 business_context: Dict[str, Any] = None, resource_constraints: Dict[str, Any] = None,
                 timeline_requirements: Dict[str, Any] = None):
        self.business_objectives = business_objectives
        self.audience = audience
        self.business_context = business_context or {}
        self.resource_constraints = resource_constraints or {}
        self.timeline_requirements = timeline_requirements or {}

class DataInsights:
    """Data insights generated by LLM analysis"""
    
    def __init__(self, key_findings: List[str], business_impact: Dict[str, Any],
                 strategic_implications: List[str], confidence_level: float):
        self.key_findings = key_findings
        self.business_impact = business_impact
        self.strategic_implications = strategic_implications
        self.confidence_level = confidence_level

class ExecutiveSummary:
    """Executive summary with key findings and strategic implications"""
    
    def __init__(self, key_findings: List[str], business_impact: str,
                 strategic_implications: List[str], urgency_level: str):
        self.key_findings = key_findings
        self.business_impact = business_impact
        self.strategic_implications = strategic_implications
        self.urgency_level = urgency_level

class Recommendation:
    """Actionable business recommendation"""
    
    def __init__(self, title: str, description: str, priority: str,
                 risk_assessment: str, resource_requirements: Dict[str, Any],
                 timeline: str, expected_impact: str):
        self.title = title
        self.description = description
        self.priority = priority
        self.risk_assessment = risk_assessment
        self.resource_requirements = resource_requirements
        self.timeline = timeline
        self.expected_impact = expected_impact
    
    @classmethod
    def list_from_llm_response(cls, llm_response: LLMResponse) -> List['Recommendation']:
        """Create list of recommendations from LLM response"""
        try:
            data = json.loads(llm_response.content)
            recommendations = []
            
            for rec_data in data.get('recommendations', []):
                recommendations.append(cls(
                    title=rec_data.get('title', ''),
                    description=rec_data.get('description', ''),
                    priority=rec_data.get('priority', 'Medium'),
                    risk_assessment=rec_data.get('risk_assessment', ''),
                    resource_requirements=rec_data.get('resource_requirements', {}),
                    timeline=rec_data.get('timeline', ''),
                    expected_impact=rec_data.get('expected_impact', '')
                ))
            
            return recommendations
        except (json.JSONDecodeError, KeyError):
            return []

# Compatibility alias
Report = IntelligentReport


class LLMEnhancedReportAgent(BaseAgent):
    """LLM-Enhanced Agent responsible for generating intelligent executive reports"""
    
    def __init__(self):
        super().__init__("LLMEnhancedReportAgent")
        self.report_templates = {}
        self.output_directory = "./reports"
        self.llm_service = None
        
    async def initialize(self):
        """Initialize LLM-Enhanced Report Agent resources"""
        try:
            # Initialize LLM service
            self.llm_service = get_openai_service()
            
            # Create output directory
            os.makedirs(self.output_directory, exist_ok=True)
            
            # Load report templates
            await self._load_report_templates()
            
            # Initialize report generators
            await self._initialize_generators()
            
            # Load LLM prompt templates for report generation
            await self._load_llm_templates()
            
            self.logger.info("LLM-Enhanced Report Agent initialized", output_dir=self.output_directory)
            
        except Exception as e:
            self.logger.error("Failed to initialize LLM-Enhanced Report Agent", error=str(e))
            raise
    
    async def cleanup(self):
        """Cleanup resources"""
        self.logger.info("Report Agent cleaned up")
    
    async def process(self, data: Dict[str, Any]) -> IntelligentReport:
        """Process intelligent report generation request"""
        if isinstance(data, dict) and 'query_result' in data:
            query_result = data['query_result']
            format = ReportFormat(data.get('format', 'pdf'))
            template = ReportTemplate(data.get('template', 'executive_summary'))
            title = data.get('title', 'Relatório Executivo')
            
            # Create report context
            report_context = ReportContext(
                business_objectives=data.get('business_objectives', ['Análise fiscal executiva']),
                audience=data.get('audience', 'executive'),
                business_context=data.get('business_context', {}),
                resource_constraints=data.get('resource_constraints', {}),
                timeline_requirements=data.get('timeline_requirements', {})
            )
            
            return await self.generate_intelligent_report(query_result, report_context, format, template, title)
        return None
    
    async def _load_report_templates(self):
        """Load report templates"""
        try:
            self.report_templates = {
                ReportTemplate.EXECUTIVE_SUMMARY: {
                    'title': 'Relatório Executivo',
                    'sections': [
                        'summary',
                        'key_metrics',
                        'trends',
                        'recommendations'
                    ],
                    'charts': ['summary_chart', 'trend_chart']
                },
                
                ReportTemplate.SUPPLIER_ANALYSIS: {
                    'title': 'Análise de Fornecedores',
                    'sections': [
                        'supplier_overview',
                        'top_suppliers',
                        'regional_distribution',
                        'performance_metrics'
                    ],
                    'charts': ['supplier_pie_chart', 'regional_bar_chart']
                },
                
                ReportTemplate.PRODUCT_ANALYSIS: {
                    'title': 'Análise de Produtos',
                    'sections': [
                        'product_overview',
                        'category_analysis',
                        'top_products',
                        'price_trends'
                    ],
                    'charts': ['category_chart', 'price_trend_chart']
                },
                
                ReportTemplate.TAX_ANALYSIS: {
                    'title': 'Análise Tributária',
                    'sections': [
                        'tax_overview',
                        'tax_by_type',
                        'tax_efficiency',
                        'compliance_status'
                    ],
                    'charts': ['tax_breakdown_chart', 'efficiency_chart']
                },
                
                ReportTemplate.MONTHLY_REPORT: {
                    'title': 'Relatório Mensal',
                    'sections': [
                        'monthly_summary',
                        'comparison',
                        'highlights',
                        'action_items'
                    ],
                    'charts': ['monthly_trend_chart', 'comparison_chart']
                }
            }
            
            self.logger.info("Report templates loaded", templates=len(self.report_templates))
            
        except Exception as e:
            self.logger.error("Error loading report templates", error=str(e))
    
    async def _load_llm_templates(self):
        """Load LLM prompt templates for intelligent report generation"""
        try:
            # Add report-specific prompt templates to the LLM service
            if self.llm_service and hasattr(self.llm_service, 'prompt_manager'):
                # Add data insight generation template
                self.llm_service.prompt_manager.templates["data_insight_generation"] = """
Você é um especialista em business intelligence especializado em análise de dados fiscais brasileiros para executivos C-level.

DADOS PARA ANÁLISE:
Resumo dos Dados: {data_summary}
Análise Estatística: {statistical_analysis}
Comparação Histórica: {historical_comparison}
Contexto de Mercado: {market_context}
Objetivos Empresariais: {business_objectives}
Público-Alvo: {audience}

CONTEXTO BRASILEIRO:
- Moeda: Real (R$)
- Formato de data: DD/MM/AAAA
- Tipos de documentos: NF-e, NFS-e
- Impostos principais: ICMS, IPI, PIS, COFINS, ISS

INSTRUÇÕES:
1. Analise os dados identificando:
   - Padrões significativos nos valores e volumes
   - Tendências temporais e sazonais
   - Anomalias ou desvios importantes
   - Oportunidades de otimização fiscal

2. Gere insights de nível executivo incluindo:
   - Principais descobertas e sua significância empresarial
   - Tendências e padrões com implicações estratégicas
   - Oportunidades e riscos identificados
   - Performance contra benchmarks do setor
   - Impactos financeiros quantificados

3. Foque em insights acionáveis para tomada de decisão

RESPOSTA EM JSON:
{{
    "key_findings": ["descoberta 1", "descoberta 2", "descoberta 3"],
    "trends_identified": ["tendência 1", "tendência 2"],
    "business_impact": {{
        "financial_impact": "impacto financeiro quantificado",
        "operational_impact": "impacto operacional",
        "strategic_impact": "impacto estratégico"
    }},
    "strategic_implications": ["implicação 1", "implicação 2"],
    "opportunities": ["oportunidade 1", "oportunidade 2"],
    "risks": ["risco 1", "risco 2"],
    "confidence_level": 0.85,
    "supporting_data": {{
        "key_metrics": {{}},
        "benchmarks": {{}}
    }}
}}
"""
                
                # Add executive summary generation template
                self.llm_service.prompt_manager.templates["executive_summary_generation"] = """
Você é um consultor executivo especializado em comunicação C-level para o mercado brasileiro.

DADOS DE ENTRADA:
Principais Descobertas: {key_findings}
Impacto Empresarial: {business_impact}
Métricas Críticas: {critical_metrics}
Implicações Estratégicas: {strategic_implications}
Nível de Urgência: {urgency_level}
Cargo do Público: {audience_role}

CONTEXTO EXECUTIVO:
- Estilo: Direto, objetivo, focado em resultados
- Linguagem: Português brasileiro executivo
- Foco: Impactos financeiros e estratégicos
- Formato: Resumo executivo estruturado

INSTRUÇÕES:
1. Crie um resumo executivo que inclua:
   - Situação atual em 2-3 frases
   - Principais descobertas com impacto quantificado
   - Implicações estratégicas prioritárias
   - Nível de urgência e próximos passos

2. Use linguagem executiva clara e objetiva
3. Quantifique impactos sempre que possível
4. Priorize informações por relevância estratégica

RESPOSTA EM JSON:
{{
    "executive_overview": "visão geral da situação em 2-3 frases",
    "key_findings_summary": ["descoberta prioritária 1", "descoberta prioritária 2"],
    "business_impact_summary": "resumo do impacto empresarial quantificado",
    "strategic_implications_summary": ["implicação estratégica 1", "implicação estratégica 2"],
    "urgency_assessment": "Alto/Médio/Baixo",
    "next_steps": ["próximo passo 1", "próximo passo 2"],
    "confidence_level": 0.9
}}
"""
                
                # Add recommendation generation template
                self.llm_service.prompt_manager.templates["recommendation_generation"] = """
Você é um consultor estratégico especializado em otimização fiscal e operacional para empresas brasileiras.

CONTEXTO PARA RECOMENDAÇÕES:
Insights Analisados: {insights}
Contexto Empresarial: {business_context}
Ações Disponíveis: {available_actions}
Avaliação de Riscos: {risk_assessment}
Restrições de Recursos: {resource_constraints}
Requisitos de Cronograma: {timeline_requirements}

DIRETRIZES BRASILEIRAS:
- Conformidade fiscal: Receita Federal, SEFAZ
- Regulamentações: CFC, CVM quando aplicável
- Práticas de mercado: Benchmarks do setor
- Aspectos tributários: Planejamento fiscal legal

INSTRUÇÕES:
1. Gere recomendações acionáveis que incluam:
   - Título claro e objetivo
   - Descrição detalhada da ação
   - Prioridade (Alta/Média/Baixa)
   - Avaliação de risco
   - Recursos necessários
   - Cronograma estimado
   - Impacto esperado quantificado

2. Priorize recomendações por:
   - Impacto financeiro
   - Facilidade de implementação
   - Alinhamento estratégico
   - Urgência

3. Considere restrições de recursos e cronograma

RESPOSTA EM JSON:
{{
    "recommendations": [
        {{
            "title": "Título da Recomendação",
            "description": "Descrição detalhada da ação recomendada",
            "priority": "Alta/Média/Baixa",
            "risk_assessment": "avaliação de risco da implementação",
            "resource_requirements": {{
                "financial": "recursos financeiros necessários",
                "human": "recursos humanos necessários",
                "technical": "recursos técnicos necessários"
            }},
            "timeline": "cronograma estimado de implementação",
            "expected_impact": "impacto esperado quantificado",
            "success_metrics": ["métrica 1", "métrica 2"]
        }}
    ],
    "implementation_priority": ["recomendação 1", "recomendação 2"],
    "risk_mitigation": ["estratégia de mitigação 1", "estratégia de mitigação 2"]
}}
"""
            
            self.logger.info("LLM templates loaded for report generation")
            
        except Exception as e:
            self.logger.error("Error loading LLM templates", error=str(e))
    
    async def _initialize_generators(self):
        """Initialize report format generators"""
        try:
            # In a real implementation, you would initialize:
            # - reportlab for PDF generation
            # - openpyxl for Excel generation
            # - python-docx for Word generation
            
            self.logger.info("Report generators initialized")
            
        except Exception as e:
            self.logger.error("Error initializing generators", error=str(e))
    
    async def generate_intelligent_report(self, query_result: Dict[str, Any], 
                                        report_context: ReportContext,
                                        format: ReportFormat = ReportFormat.PDF, 
                                        template: ReportTemplate = ReportTemplate.EXECUTIVE_SUMMARY,
                                        title: str = None) -> IntelligentReport:
        """Generate intelligent report with LLM-powered insights and recommendations"""
        try:
            start_time = datetime.now()
            self.logger.info("Generating intelligent report", format=format.value, template=template.value)
            
            # Create intelligent report object
            report_title = title or self.report_templates[template]['title']
            report = IntelligentReport(report_title, format, template)
            
            # Process data for report
            report.content = await self._process_data_for_report(query_result, template)
            
            # Generate LLM-powered data insights
            report.insights = await self._generate_data_insights(query_result, report_context)
            
            # Create executive summary
            report.executive_summary = await self._create_executive_summary(
                query_result, report.insights, report_context
            )
            
            # Generate actionable recommendations
            report.recommendations = await self._generate_recommendations(
                query_result, report.insights, report_context
            )
            
            # Generate visualizations with LLM suggestions
            report.content['charts'] = await self.create_visualizations(query_result, template)
            
            # Apply executive template formatting
            formatted_report = await self.apply_executive_template(report)
            
            # Export to specified format
            exported_report = await self.export_report(formatted_report, format)
            
            # Calculate processing statistics
            processing_time = (datetime.now() - start_time).total_seconds()
            exported_report.llm_processing_stats = {
                'processing_time_seconds': processing_time,
                'insights_confidence': report.insights.confidence_level if report.insights else 0.0,
                'recommendations_count': len(report.recommendations),
                'template_used': template.value,
                'llm_calls_made': 3  # insights + summary + recommendations
            }
            
            self.logger.info("Intelligent report generated successfully", 
                           file_path=exported_report.file_path,
                           size=f"{exported_report.size_bytes} bytes",
                           processing_time=f"{processing_time:.2f}s",
                           insights_confidence=exported_report.llm_processing_stats['insights_confidence'])
            
            return exported_report
            
        except Exception as e:
            self.logger.error("Error generating intelligent report", error=str(e))
            raise
    
    async def _process_data_for_report(self, query_result: Dict[str, Any], template: ReportTemplate) -> Dict[str, Any]:
        """Process query result data for report template"""
        
        data = query_result.get('data', [])
        metadata = query_result.get('metadata', {})
        
        processed_content = {
            'raw_data': data,
            'metadata': metadata,
            'summary': await self._generate_summary(data),
            'sections': {}
        }
        
        # Process data based on template
        template_config = self.report_templates[template]
        
        for section in template_config['sections']:
            processed_content['sections'][section] = await self._process_section(section, data)
        
        return processed_content
    
    async def _generate_summary(self, data: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate executive summary from data"""
        if not data:
            return {'message': 'Nenhum dado disponível para análise'}
        
        summary = {
            'total_records': len(data),
            'date_range': 'Último período analisado',
            'key_insights': []
        }
        
        # Generate key insights based on data
        if data:
            # Find numeric columns for analysis
            numeric_columns = []
            for key, value in data[0].items():
                if isinstance(value, (int, float)):
                    numeric_columns.append(key)
            
            # Calculate totals and averages
            for col in numeric_columns:
                values = [row.get(col, 0) for row in data if row.get(col) is not None]
                if values:
                    total = sum(values)
                    avg = total / len(values)
                    summary[f'total_{col}'] = total
                    summary[f'avg_{col}'] = avg
            
            # Generate insights
            if 'valor_total' in data[0] or 'total_value' in data[0]:
                summary['key_insights'].append('Análise de valores totais concluída')
            
            if len(data) > 10:
                summary['key_insights'].append(f'Dataset robusto com {len(data)} registros')
            
            summary['key_insights'].append('Dados processados com sucesso')
        
        return summary
    
    async def _process_section(self, section: str, data: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Process specific report section"""
        
        if section == 'supplier_overview':
            return {
                'title': 'Visão Geral dos Fornecedores',
                'content': f'Análise de {len(data)} registros de fornecedores',
                'data': data[:10]  # Top 10
            }
        
        elif section == 'top_suppliers':
            # Sort by value if available
            sorted_data = sorted(data, key=lambda x: x.get('total_value', x.get('valor_total', 0)), reverse=True)
            return {
                'title': 'Principais Fornecedores',
                'content': 'Ranking dos fornecedores por valor',
                'data': sorted_data[:5]
            }
        
        elif section == 'key_metrics':
            return {
                'title': 'Métricas Principais',
                'content': 'Indicadores chave de performance',
                'metrics': await self._calculate_key_metrics(data)
            }
        
        elif section == 'trends':
            return {
                'title': 'Tendências',
                'content': 'Análise de tendências identificadas',
                'trends': ['Crescimento estável', 'Diversificação de fornecedores']
            }
        
        elif section == 'recommendations':
            return {
                'title': 'Recomendações',
                'content': 'Recomendações estratégicas baseadas na análise',
                'recommendations': [
                    'Manter relacionamento com fornecedores principais',
                    'Avaliar oportunidades de otimização fiscal',
                    'Monitorar tendências de mercado'
                ]
            }
        
        else:
            return {
                'title': section.replace('_', ' ').title(),
                'content': f'Seção {section} processada',
                'data': data[:5]
            }
    
    async def _calculate_key_metrics(self, data: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Calculate key business metrics"""
        if not data:
            return {}
        
        metrics = {}
        
        # Find numeric columns
        numeric_columns = []
        for key, value in data[0].items():
            if isinstance(value, (int, float)):
                numeric_columns.append(key)
        
        # Calculate metrics for each numeric column
        for col in numeric_columns:
            values = [row.get(col, 0) for row in data if row.get(col) is not None]
            if values:
                metrics[f'{col}_total'] = sum(values)
                metrics[f'{col}_average'] = sum(values) / len(values)
                metrics[f'{col}_max'] = max(values)
                metrics[f'{col}_min'] = min(values)
        
        return metrics
    
    async def _generate_data_insights(self, query_result: Dict[str, Any], 
                                    report_context: ReportContext) -> DataInsights:
        """Use LLM to analyze data and generate business insights"""
        try:
            self.logger.info("Generating data insights using LLM")
            
            # Prepare data summary
            data_summary = await self._create_data_summary(query_result)
            
            # Perform statistical analysis
            statistical_analysis = await self._perform_statistical_analysis(query_result)
            
            # Get historical comparison
            historical_comparison = await self._get_historical_comparison(query_result, report_context)
            
            # Get market context
            market_context = await self._get_market_context(report_context)
            
            # Prepare context for LLM
            llm_context = {
                'data_summary': data_summary,
                'statistical_analysis': statistical_analysis,
                'historical_comparison': historical_comparison,
                'market_context': market_context,
                'business_objectives': report_context.business_objectives,
                'audience': report_context.audience
            }
            
            # Generate insights using LLM
            llm_response = await self.llm_service.generate_completion(
                "data_insight_generation", 
                llm_context,
                model="gpt-4o-mini",
                temperature=0.2
            )
            
            # Parse LLM response
            try:
                insights_data = json.loads(llm_response.content)
                
                insights = DataInsights(
                    key_findings=insights_data.get('key_findings', []),
                    business_impact=insights_data.get('business_impact', {}),
                    strategic_implications=insights_data.get('strategic_implications', []),
                    confidence_level=insights_data.get('confidence_level', llm_response.confidence_score)
                )
                
                self.logger.info("Data insights generated successfully", 
                               findings_count=len(insights.key_findings),
                               confidence=insights.confidence_level)
                
                return insights
                
            except json.JSONDecodeError:
                self.logger.warning("Failed to parse LLM insights response, using fallback")
                return DataInsights(
                    key_findings=[llm_response.content],
                    business_impact={'raw_analysis': llm_response.content},
                    strategic_implications=['Análise detalhada disponível no conteúdo do relatório'],
                    confidence_level=llm_response.confidence_score
                )
                
        except Exception as e:
            self.logger.error("Error generating data insights", error=str(e))
            # Return fallback insights
            return DataInsights(
                key_findings=['Análise de dados concluída com sucesso'],
                business_impact={'status': 'Dados processados'},
                strategic_implications=['Revisar dados para insights adicionais'],
                confidence_level=0.5
            )
    
    async def _create_data_summary(self, query_result: Dict[str, Any]) -> Dict[str, Any]:
        """Create comprehensive data summary for LLM analysis"""
        try:
            data = query_result.get('data', [])
            metadata = query_result.get('metadata', {})
            
            if not data:
                return {'message': 'Nenhum dado disponível para análise'}
            
            summary = {
                'total_records': len(data),
                'data_period': metadata.get('period', 'Período não especificado'),
                'data_source': metadata.get('source', 'Documentos fiscais'),
                'columns': list(data[0].keys()) if data else [],
                'sample_records': data[:3] if len(data) >= 3 else data
            }
            
            # Analyze numeric columns
            numeric_columns = []
            for key, value in (data[0].items() if data else []):
                if isinstance(value, (int, float)):
                    numeric_columns.append(key)
            
            # Calculate aggregations for numeric columns
            for col in numeric_columns:
                values = [row.get(col, 0) for row in data if row.get(col) is not None]
                if values:
                    summary[f'{col}_total'] = sum(values)
                    summary[f'{col}_average'] = sum(values) / len(values)
                    summary[f'{col}_max'] = max(values)
                    summary[f'{col}_min'] = min(values)
                    summary[f'{col}_count'] = len(values)
            
            # Identify categorical columns and their distributions
            categorical_summary = {}
            for col in summary['columns']:
                if col not in numeric_columns:
                    values = [str(row.get(col, '')) for row in data if row.get(col) is not None]
                    unique_values = list(set(values))
                    if len(unique_values) <= 20:  # Only for columns with reasonable number of unique values
                        categorical_summary[col] = {
                            'unique_count': len(unique_values),
                            'top_values': unique_values[:5]
                        }
            
            summary['categorical_analysis'] = categorical_summary
            
            return summary
            
        except Exception as e:
            self.logger.error("Error creating data summary", error=str(e))
            return {'error': 'Erro ao criar resumo dos dados'}
    
    async def _perform_statistical_analysis(self, query_result: Dict[str, Any]) -> Dict[str, Any]:
        """Perform statistical analysis on the data"""
        try:
            data = query_result.get('data', [])
            
            if not data:
                return {'message': 'Dados insuficientes para análise estatística'}
            
            analysis = {
                'record_count': len(data),
                'data_quality': 'Boa' if len(data) > 10 else 'Limitada'
            }
            
            # Find numeric columns for statistical analysis
            numeric_columns = []
            for key, value in (data[0].items() if data else []):
                if isinstance(value, (int, float)):
                    numeric_columns.append(key)
            
            # Perform statistical calculations
            for col in numeric_columns:
                values = [row.get(col, 0) for row in data if row.get(col) is not None and row.get(col) != 0]
                if values and len(values) > 1:
                    mean_val = sum(values) / len(values)
                    variance = sum((x - mean_val) ** 2 for x in values) / len(values)
                    std_dev = variance ** 0.5
                    
                    analysis[f'{col}_statistics'] = {
                        'mean': mean_val,
                        'std_deviation': std_dev,
                        'coefficient_variation': (std_dev / mean_val) * 100 if mean_val != 0 else 0,
                        'range': max(values) - min(values),
                        'median': sorted(values)[len(values) // 2]
                    }
            
            # Identify trends if temporal data is available
            if any('data' in col.lower() or 'date' in col.lower() for col in (data[0].keys() if data else [])):
                analysis['temporal_analysis'] = 'Dados temporais identificados - análise de tendência possível'
            
            return analysis
            
        except Exception as e:
            self.logger.error("Error performing statistical analysis", error=str(e))
            return {'error': 'Erro na análise estatística'}
    
    async def _get_historical_comparison(self, query_result: Dict[str, Any], 
                                       report_context: ReportContext) -> Dict[str, Any]:
        """Get historical comparison context"""
        try:
            # This would typically query historical data from the database
            # For now, we'll provide a structured placeholder
            
            comparison = {
                'comparison_period': 'Últimos 12 meses',
                'baseline_established': True,
                'growth_indicators': {
                    'volume_growth': 'Estável',
                    'value_growth': 'Crescimento moderado',
                    'supplier_diversity': 'Mantida'
                },
                'seasonal_patterns': {
                    'identified': True,
                    'peak_months': ['Dezembro', 'Janeiro'],
                    'low_months': ['Julho', 'Agosto']
                },
                'anomalies_detected': []
            }
            
            # Analyze current data for comparison insights
            data = query_result.get('data', [])
            if data:
                total_records = len(data)
                if total_records > 100:
                    comparison['data_volume_assessment'] = 'Volume alto - análise robusta possível'
                elif total_records > 20:
                    comparison['data_volume_assessment'] = 'Volume moderado - análise confiável'
                else:
                    comparison['data_volume_assessment'] = 'Volume baixo - análise limitada'
            
            return comparison
            
        except Exception as e:
            self.logger.error("Error getting historical comparison", error=str(e))
            return {'error': 'Comparação histórica não disponível'}
    
    async def _get_market_context(self, report_context: ReportContext) -> Dict[str, Any]:
        """Get market context for business analysis"""
        try:
            # This would typically integrate with market data APIs
            # For now, we'll provide Brazilian market context
            
            context = {
                'market_environment': 'Mercado brasileiro',
                'economic_indicators': {
                    'inflation_trend': 'Controlada',
                    'interest_rates': 'Em ajuste',
                    'business_confidence': 'Moderada'
                },
                'regulatory_environment': {
                    'tax_changes': 'Estável',
                    'compliance_requirements': 'Rigorosos',
                    'digital_transformation': 'Em andamento'
                },
                'industry_trends': {
                    'digitalization': 'Acelerada',
                    'sustainability_focus': 'Crescente',
                    'supply_chain_optimization': 'Prioritária'
                },
                'business_sector': report_context.business_context.get('sector', 'Geral')
            }
            
            return context
            
        except Exception as e:
            self.logger.error("Error getting market context", error=str(e))
            return {'market_context': 'Contexto de mercado brasileiro padrão'}
    
    async def _create_executive_summary(self, query_result: Dict[str, Any],
                                      insights: DataInsights, 
                                      report_context: ReportContext) -> Dict[str, Any]:
        """Generate executive-level summary with key findings"""
        try:
            self.logger.info("Creating executive summary using LLM")
            
            # Identify critical metrics
            critical_metrics = await self._identify_critical_metrics(query_result, report_context)
            
            # Assess urgency level
            urgency_level = await self._assess_urgency_level(insights)
            
            # Prepare context for LLM
            llm_context = {
                'key_findings': insights.key_findings,
                'business_impact': insights.business_impact,
                'critical_metrics': critical_metrics,
                'strategic_implications': insights.strategic_implications,
                'urgency_level': urgency_level,
                'audience_role': report_context.audience
            }
            
            # Generate executive summary using LLM
            llm_response = await self.llm_service.generate_completion(
                "executive_summary_generation",
                llm_context,
                model="gpt-4o-mini",
                temperature=0.1  # Lower temperature for more consistent executive communication
            )
            
            # Parse LLM response
            try:
                summary_data = json.loads(llm_response.content)
                
                executive_summary = {
                    'executive_overview': summary_data.get('executive_overview', ''),
                    'key_findings_summary': summary_data.get('key_findings_summary', []),
                    'business_impact_summary': summary_data.get('business_impact_summary', ''),
                    'strategic_implications_summary': summary_data.get('strategic_implications_summary', []),
                    'urgency_assessment': summary_data.get('urgency_assessment', urgency_level),
                    'next_steps': summary_data.get('next_steps', []),
                    'confidence_level': summary_data.get('confidence_level', llm_response.confidence_score),
                    'generated_at': datetime.now().isoformat()
                }
                
                self.logger.info("Executive summary created successfully",
                               urgency=executive_summary['urgency_assessment'],
                               confidence=executive_summary['confidence_level'])
                
                return executive_summary
                
            except json.JSONDecodeError:
                self.logger.warning("Failed to parse executive summary response, using fallback")
                return {
                    'executive_overview': llm_response.content,
                    'key_findings_summary': insights.key_findings[:3],
                    'business_impact_summary': str(insights.business_impact),
                    'strategic_implications_summary': insights.strategic_implications[:2],
                    'urgency_assessment': urgency_level,
                    'next_steps': ['Revisar análise detalhada', 'Implementar recomendações'],
                    'confidence_level': llm_response.confidence_score,
                    'generated_at': datetime.now().isoformat()
                }
                
        except Exception as e:
            self.logger.error("Error creating executive summary", error=str(e))
            # Return fallback summary
            return {
                'executive_overview': 'Análise fiscal executiva concluída com dados processados com sucesso.',
                'key_findings_summary': insights.key_findings[:3] if insights.key_findings else ['Dados analisados'],
                'business_impact_summary': 'Impacto empresarial identificado nos dados analisados.',
                'strategic_implications_summary': insights.strategic_implications[:2] if insights.strategic_implications else ['Revisar estratégia'],
                'urgency_assessment': 'Médio',
                'next_steps': ['Revisar relatório completo', 'Avaliar recomendações'],
                'confidence_level': 0.6,
                'generated_at': datetime.now().isoformat()
            }
    
    async def _identify_critical_metrics(self, query_result: Dict[str, Any], 
                                       report_context: ReportContext) -> Dict[str, Any]:
        """Identify critical business metrics from the data"""
        try:
            data = query_result.get('data', [])
            
            if not data:
                return {'message': 'Nenhuma métrica disponível'}
            
            critical_metrics = {}
            
            # Find key financial metrics
            financial_columns = [col for col in data[0].keys() if any(
                keyword in col.lower() for keyword in ['valor', 'total', 'amount', 'price', 'custo']
            )]
            
            for col in financial_columns:
                values = [row.get(col, 0) for row in data if isinstance(row.get(col), (int, float))]
                if values:
                    critical_metrics[f'{col}_total'] = sum(values)
                    critical_metrics[f'{col}_average'] = sum(values) / len(values)
                    critical_metrics[f'{col}_trend'] = 'Crescente' if len(values) > 1 and values[-1] > values[0] else 'Estável'
            
            # Volume metrics
            critical_metrics['transaction_volume'] = len(data)
            critical_metrics['data_quality_score'] = min(100, (len(data) / 10) * 10)  # Simple quality score
            
            # Business context metrics
            if 'fornecedor' in str(data[0]).lower() or 'supplier' in str(data[0]).lower():
                suppliers = set(str(row.get('razao_social', row.get('supplier_name', ''))) for row in data)
                critical_metrics['supplier_diversity'] = len(suppliers)
            
            # Time-based metrics if date columns exist
            date_columns = [col for col in data[0].keys() if 'data' in col.lower() or 'date' in col.lower()]
            if date_columns:
                critical_metrics['time_span_analysis'] = 'Dados temporais disponíveis'
            
            return critical_metrics
            
        except Exception as e:
            self.logger.error("Error identifying critical metrics", error=str(e))
            return {'error': 'Erro ao identificar métricas críticas'}
    
    async def _assess_urgency_level(self, insights: DataInsights) -> str:
        """Assess urgency level based on insights"""
        try:
            urgency_score = 0
            
            # Check for high-impact findings
            if insights.business_impact:
                impact_indicators = str(insights.business_impact).lower()
                if any(keyword in impact_indicators for keyword in ['crítico', 'urgente', 'alto', 'significativo']):
                    urgency_score += 2
                elif any(keyword in impact_indicators for keyword in ['moderado', 'médio']):
                    urgency_score += 1
            
            # Check strategic implications
            if insights.strategic_implications:
                strategic_text = ' '.join(insights.strategic_implications).lower()
                if any(keyword in strategic_text for keyword in ['imediato', 'urgente', 'crítico']):
                    urgency_score += 2
                elif any(keyword in strategic_text for keyword in ['importante', 'relevante']):
                    urgency_score += 1
            
            # Check confidence level
            if insights.confidence_level > 0.8:
                urgency_score += 1
            
            # Determine urgency level
            if urgency_score >= 4:
                return 'Alto'
            elif urgency_score >= 2:
                return 'Médio'
            else:
                return 'Baixo'
                
        except Exception as e:
            self.logger.error("Error assessing urgency level", error=str(e))
            return 'Médio'
    
    async def _generate_recommendations(self, query_result: Dict[str, Any],
                                      insights: DataInsights, 
                                      report_context: ReportContext) -> List[Recommendation]:
        """Generate actionable business recommendations"""
        try:
            self.logger.info("Generating actionable recommendations using LLM")
            
            # Get available actions based on business context
            available_actions = await self._get_available_actions(report_context)
            
            # Assess risks from insights
            risk_assessment = await self._assess_risks(insights)
            
            # Prepare context for LLM
            llm_context = {
                'insights': {
                    'key_findings': insights.key_findings,
                    'business_impact': insights.business_impact,
                    'strategic_implications': insights.strategic_implications,
                    'confidence_level': insights.confidence_level
                },
                'business_context': report_context.business_context,
                'available_actions': available_actions,
                'risk_assessment': risk_assessment,
                'resource_constraints': report_context.resource_constraints,
                'timeline_requirements': report_context.timeline_requirements
            }
            
            # Generate recommendations using LLM
            llm_response = await self.llm_service.generate_completion(
                "recommendation_generation",
                llm_context,
                model="gpt-4o-mini",
                temperature=0.3  # Moderate temperature for creative but practical recommendations
            )
            
            # Parse LLM response and create Recommendation objects
            recommendations = Recommendation.list_from_llm_response(llm_response)
            
            if not recommendations:
                # Fallback recommendations based on insights
                recommendations = await self._create_fallback_recommendations(insights, report_context)
            
            self.logger.info("Recommendations generated successfully", 
                           count=len(recommendations))
            
            return recommendations
            
        except Exception as e:
            self.logger.error("Error generating recommendations", error=str(e))
            # Return fallback recommendations
            return await self._create_fallback_recommendations(insights, report_context)
    
    async def _get_available_actions(self, report_context: ReportContext) -> List[Dict[str, Any]]:
        """Get available actions based on business context"""
        try:
            # Standard actions available for fiscal analysis
            standard_actions = [
                {
                    'category': 'Otimização Fiscal',
                    'actions': [
                        'Revisar classificação fiscal de produtos',
                        'Otimizar regime tributário',
                        'Implementar planejamento fiscal',
                        'Revisar benefícios fiscais disponíveis'
                    ]
                },
                {
                    'category': 'Gestão de Fornecedores',
                    'actions': [
                        'Diversificar base de fornecedores',
                        'Renegociar contratos principais',
                        'Implementar avaliação de performance',
                        'Otimizar relacionamentos estratégicos'
                    ]
                },
                {
                    'category': 'Processos Operacionais',
                    'actions': [
                        'Automatizar processamento de documentos',
                        'Implementar controles de qualidade',
                        'Otimizar fluxos de aprovação',
                        'Melhorar rastreabilidade de dados'
                    ]
                },
                {
                    'category': 'Análise e Monitoramento',
                    'actions': [
                        'Implementar dashboards executivos',
                        'Criar alertas automáticos',
                        'Estabelecer KPIs de performance',
                        'Implementar análise preditiva'
                    ]
                }
            ]
            
            # Filter actions based on business context
            business_sector = report_context.business_context.get('sector', 'geral')
            if business_sector.lower() in ['industrial', 'manufatura']:
                standard_actions.append({
                    'category': 'Específico Industrial',
                    'actions': [
                        'Otimizar IPI e ICMS',
                        'Revisar classificação NCM',
                        'Implementar controle de estoque fiscal'
                    ]
                })
            elif business_sector.lower() in ['serviços', 'consultoria']:
                standard_actions.append({
                    'category': 'Específico Serviços',
                    'actions': [
                        'Otimizar ISS',
                        'Revisar retenções na fonte',
                        'Implementar controle de prestação de serviços'
                    ]
                })
            
            return standard_actions
            
        except Exception as e:
            self.logger.error("Error getting available actions", error=str(e))
            return []
    
    async def _assess_risks(self, insights: DataInsights) -> Dict[str, Any]:
        """Assess risks based on insights"""
        try:
            risk_assessment = {
                'overall_risk_level': 'Médio',
                'identified_risks': [],
                'mitigation_strategies': []
            }
            
            # Analyze insights for risk indicators
            risk_keywords = ['anomalia', 'desvio', 'inconsistência', 'problema', 'erro', 'falha']
            
            # Check key findings for risks
            for finding in insights.key_findings:
                if any(keyword in finding.lower() for keyword in risk_keywords):
                    risk_assessment['identified_risks'].append(f"Risco identificado: {finding}")
                    risk_assessment['overall_risk_level'] = 'Alto'
            
            # Check business impact for financial risks
            if insights.business_impact:
                impact_text = str(insights.business_impact).lower()
                if any(keyword in impact_text for keyword in ['perda', 'redução', 'queda', 'negativo']):
                    risk_assessment['identified_risks'].append("Risco financeiro identificado no impacto empresarial")
                    if risk_assessment['overall_risk_level'] == 'Médio':
                        risk_assessment['overall_risk_level'] = 'Alto'
            
            # Add mitigation strategies based on risk level
            if risk_assessment['overall_risk_level'] == 'Alto':
                risk_assessment['mitigation_strategies'] = [
                    'Implementar monitoramento contínuo',
                    'Estabelecer controles adicionais',
                    'Revisar processos críticos',
                    'Criar plano de contingência'
                ]
            elif risk_assessment['overall_risk_level'] == 'Médio':
                risk_assessment['mitigation_strategies'] = [
                    'Monitorar indicadores chave',
                    'Revisar controles existentes',
                    'Implementar alertas preventivos'
                ]
            else:
                risk_assessment['mitigation_strategies'] = [
                    'Manter monitoramento regular',
                    'Revisar periodicamente'
                ]
            
            # Consider confidence level in risk assessment
            if insights.confidence_level < 0.7:
                risk_assessment['identified_risks'].append("Risco de análise: Baixa confiança nos dados")
                risk_assessment['mitigation_strategies'].append("Melhorar qualidade dos dados")
            
            return risk_assessment
            
        except Exception as e:
            self.logger.error("Error assessing risks", error=str(e))
            return {
                'overall_risk_level': 'Médio',
                'identified_risks': ['Erro na avaliação de riscos'],
                'mitigation_strategies': ['Revisar análise manualmente']
            }
    
    async def _create_fallback_recommendations(self, insights: DataInsights, 
                                             report_context: ReportContext) -> List[Recommendation]:
        """Create fallback recommendations when LLM generation fails"""
        try:
            recommendations = []
            
            # Standard recommendation based on insights
            if insights.key_findings:
                recommendations.append(Recommendation(
                    title="Revisar Principais Descobertas",
                    description=f"Analisar em detalhes as descobertas identificadas: {', '.join(insights.key_findings[:2])}",
                    priority="Alta",
                    risk_assessment="Baixo",
                    resource_requirements={
                        'financial': 'Mínimo',
                        'human': '2-4 horas de análise',
                        'technical': 'Não requerido'
                    },
                    timeline="1-2 semanas",
                    expected_impact="Melhor compreensão dos dados e identificação de oportunidades"
                ))
            
            # Process improvement recommendation
            recommendations.append(Recommendation(
                title="Otimizar Processos de Análise",
                description="Implementar melhorias nos processos de coleta e análise de dados fiscais",
                priority="Média",
                risk_assessment="Baixo",
                resource_requirements={
                    'financial': 'Moderado',
                    'human': 'Equipe de TI e Fiscal',
                    'technical': 'Ferramentas de automação'
                },
                timeline="1-3 meses",
                expected_impact="Maior eficiência e precisão na análise fiscal"
            ))
            
            # Monitoring recommendation
            recommendations.append(Recommendation(
                title="Implementar Monitoramento Contínuo",
                description="Estabelecer sistema de monitoramento contínuo dos indicadores fiscais identificados",
                priority="Média",
                risk_assessment="Baixo",
                resource_requirements={
                    'financial': 'Baixo',
                    'human': 'Configuração inicial',
                    'technical': 'Dashboard e alertas'
                },
                timeline="2-4 semanas",
                expected_impact="Detecção precoce de anomalias e tendências"
            ))
            
            return recommendations
            
        except Exception as e:
            self.logger.error("Error creating fallback recommendations", error=str(e))
            return []
    
    # Backward compatibility method
    async def generate_report(self, query_result: Dict[str, Any], format: ReportFormat, 
                            template: ReportTemplate = ReportTemplate.EXECUTIVE_SUMMARY,
                            title: str = None) -> IntelligentReport:
        """Backward compatibility wrapper for generate_intelligent_report"""
        # Create default report context
        report_context = ReportContext(
            business_objectives=['Análise fiscal executiva'],
            audience='executive',
            business_context={},
            resource_constraints={},
            timeline_requirements={}
        )
        
        return await self.generate_intelligent_report(
            query_result, report_context, format, template, title
        )
    
    async def create_visualizations(self, query_result: Dict[str, Any], template: ReportTemplate) -> List[Dict[str, Any]]:
        """Create charts and visualizations for the report"""
        try:
            data = query_result.get('data', [])
            charts = []
            
            if not data:
                return charts
            
            template_config = self.report_templates[template]
            chart_types = template_config.get('charts', [])
            
            for chart_type in chart_types:
                chart = await self._create_chart(chart_type, data)
                if chart:
                    charts.append(chart)
            
            return charts
            
        except Exception as e:
            self.logger.error("Error creating visualizations", error=str(e))
            return []
    
    async def _create_chart(self, chart_type: str, data: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Create specific chart type"""
        
        # This is a placeholder implementation
        # In reality, you would use libraries like matplotlib, plotly, or Chart.js
        
        chart_config = {
            'type': chart_type,
            'title': chart_type.replace('_', ' ').title(),
            'data': data[:10],  # Limit data for charts
            'config': {
                'width': 800,
                'height': 400,
                'responsive': True
            }
        }
        
        if chart_type == 'summary_chart':
            chart_config.update({
                'chart_type': 'bar',
                'title': 'Resumo Executivo',
                'x_axis': 'categoria',
                'y_axis': 'valor'
            })
        
        elif chart_type == 'supplier_pie_chart':
            chart_config.update({
                'chart_type': 'pie',
                'title': 'Distribuição por Fornecedor',
                'label_field': 'razao_social',
                'value_field': 'total_value'
            })
        
        elif chart_type == 'trend_chart':
            chart_config.update({
                'chart_type': 'line',
                'title': 'Tendência Temporal',
                'x_axis': 'periodo',
                'y_axis': 'valor_total'
            })
        
        elif chart_type == 'regional_bar_chart':
            chart_config.update({
                'chart_type': 'bar',
                'title': 'Distribuição Regional',
                'x_axis': 'uf',
                'y_axis': 'valor_total'
            })
        
        return chart_config
    
    async def apply_executive_template(self, report: IntelligentReport) -> IntelligentReport:
        """Apply executive-level formatting to report"""
        try:
            # Add executive styling and formatting
            report.metadata.update({
                'style': 'executive',
                'font_family': 'Arial',
                'primary_color': '#1f4e79',
                'secondary_color': '#70ad47',
                'logo_path': './assets/company_logo.png',
                'header_text': f'{report.title} - {datetime.now().strftime("%B %Y")}',
                'footer_text': 'Confidencial - Uso Interno'
            })
            
            # Add executive summary to the beginning
            if 'summary' not in report.content:
                report.content['summary'] = await self._generate_summary(
                    report.content.get('raw_data', [])
                )
            
            # Ensure proper section ordering for executive consumption
            section_order = [
                'summary',
                'key_metrics',
                'charts',
                'sections',
                'recommendations'
            ]
            
            ordered_content = {}
            for section in section_order:
                if section in report.content:
                    ordered_content[section] = report.content[section]
            
            # Add any remaining sections
            for key, value in report.content.items():
                if key not in ordered_content:
                    ordered_content[key] = value
            
            report.content = ordered_content
            
            return report
            
        except Exception as e:
            self.logger.error("Error applying executive template", error=str(e))
            return report
    
    async def export_report(self, report: IntelligentReport, format: ReportFormat) -> IntelligentReport:
        """Export report to specified format"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{report.title.replace(' ', '_')}_{timestamp}.{format.value}"
            file_path = os.path.join(self.output_directory, filename)
            
            if format == ReportFormat.PDF:
                await self._export_pdf(report, file_path)
            elif format == ReportFormat.XLSX:
                await self._export_xlsx(report, file_path)
            elif format == ReportFormat.DOCX:
                await self._export_docx(report, file_path)
            
            # Update report with file information
            report.file_path = file_path
            report.size_bytes = os.path.getsize(file_path) if os.path.exists(file_path) else 0
            
            return report
            
        except Exception as e:
            self.logger.error("Error exporting report", error=str(e))
            raise
    
    async def _export_pdf(self, report: IntelligentReport, file_path: str):
        """Export report as PDF"""
        # Placeholder implementation
        # In reality, you would use reportlab or similar library
        
        # Enhanced PDF content with LLM insights
        content = f"""
        {report.title}
        Generated: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}
        
        RESUMO EXECUTIVO:
        {report.executive_summary.get('executive_overview', 'Não disponível') if report.executive_summary else 'Não disponível'}
        
        PRINCIPAIS DESCOBERTAS:
        """
        
        if report.insights and report.insights.key_findings:
            for i, finding in enumerate(report.insights.key_findings, 1):
                content += f"\n{i}. {finding}"
        
        content += f"""
        
        RECOMENDAÇÕES:
        """
        
        if report.recommendations:
            for i, rec in enumerate(report.recommendations, 1):
                content += f"\n{i}. {rec.title}: {rec.description}"
        
        content += f"""
        
        NÍVEL DE CONFIANÇA: {report.insights.confidence_level if report.insights else 'N/A'}
        
        ESTATÍSTICAS DE PROCESSAMENTO:
        {report.llm_processing_stats}
        """
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        self.logger.info("PDF report exported", file_path=file_path)
    
    async def _export_xlsx(self, report: IntelligentReport, file_path: str):
        """Export report as Excel"""
        # Placeholder implementation
        # In reality, you would use openpyxl or pandas
        
        import csv
        csv_path = file_path.replace('.xlsx', '.csv')
        
        data = report.content.get('raw_data', [])
        if data:
            with open(csv_path, 'w', newline='', encoding='utf-8') as f:
                if data:
                    writer = csv.DictWriter(f, fieldnames=data[0].keys())
                    writer.writeheader()
                    writer.writerows(data)
        
        # Rename to xlsx for now (placeholder)
        os.rename(csv_path, file_path)
        
        self.logger.info("Excel report exported", file_path=file_path)
    
    async def _export_docx(self, report: IntelligentReport, file_path: str):
        """Export report as Word document"""
        # Placeholder implementation
        # In reality, you would use python-docx
        
        # Enhanced DOCX content with LLM insights
        content = f"""
        {report.title}
        
        Generated: {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}
        
        RESUMO EXECUTIVO:
        {report.executive_summary.get('executive_overview', 'Não disponível') if report.executive_summary else 'Não disponível'}
        
        PRINCIPAIS DESCOBERTAS:
        """
        
        if report.insights and report.insights.key_findings:
            for finding in report.insights.key_findings:
                content += f"\n• {finding}"
        
        content += f"""
        
        IMPACTO EMPRESARIAL:
        {report.insights.business_impact if report.insights else 'Não disponível'}
        
        IMPLICAÇÕES ESTRATÉGICAS:
        """
        
        if report.insights and report.insights.strategic_implications:
            for implication in report.insights.strategic_implications:
                content += f"\n• {implication}"
        
        content += f"""
        
        RECOMENDAÇÕES ACIONÁVEIS:
        """
        
        if report.recommendations:
            for rec in report.recommendations:
                content += f"""
        
        {rec.title}
        Descrição: {rec.description}
        Prioridade: {rec.priority}
        Cronograma: {rec.timeline}
        Impacto Esperado: {rec.expected_impact}
        """
        
        content += f"""
        
        SEÇÕES DETALHADAS:
        """
        
        sections = report.content.get('sections', {})
        for section_name, section_data in sections.items():
            content += f"\n\n{section_data.get('title', section_name)}:\n"
            content += f"{section_data.get('content', 'No content available')}\n"
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        self.logger.info("Word report exported", file_path=file_path)
    
    async def get_report_preview(self, report: IntelligentReport) -> Dict[str, Any]:
        """Generate report preview for user validation"""
        try:
            preview = {
                'title': report.title,
                'format': report.format.value,
                'template': report.template.value,
                'created_at': report.created_at.isoformat(),
                'sections': list(report.content.get('sections', {}).keys()),
                'charts': len(report.content.get('charts', [])),
                'data_points': len(report.content.get('raw_data', [])),
                'summary': report.content.get('summary', {}),
                # LLM-enhanced preview fields
                'insights_available': report.insights is not None,
                'key_findings_count': len(report.insights.key_findings) if report.insights else 0,
                'recommendations_count': len(report.recommendations),
                'confidence_level': report.insights.confidence_level if report.insights else 0.0,
                'executive_summary_available': report.executive_summary is not None,
                'urgency_level': report.executive_summary.get('urgency_assessment', 'N/A') if report.executive_summary else 'N/A',
                'llm_processing_stats': report.llm_processing_stats
            }
            
            return preview
            
        except Exception as e:
            self.logger.error("Error generating report preview", error=str(e))
            return {'error': str(e)}
    
    async def list_available_templates(self) -> List[Dict[str, Any]]:
        """List all available report templates"""
        templates = []
        
        for template, config in self.report_templates.items():
            templates.append({
                'id': template.value,
                'title': config['title'],
                'sections': config['sections'],
                'charts': config.get('charts', [])
            })
        
        return templates

# Compatibility alias
ReportAgent = LLMEnhancedReportAgent