-- MVP Sistema Simplificado de Análise Fiscal - Simplified Database Schema
-- Optimized tables for MVP focusing on essential functionality

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Main fiscal documents table (simplified from existing fiscal_documents)
CREATE TABLE fiscal_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    filename VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'uploaded' CHECK (
        status IN ('uploaded', 'processing', 'completed', 'error')
    ),
    processing_progress INTEGER DEFAULT 0 CHECK (processing_progress >= 0 AND processing_progress <= 100),
    uploaded_at TIMESTAMP DEFAULT NOW(),
    processed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    
    -- Indexes for performance
    CONSTRAINT idx_fiscal_documents_status CHECK (status IS NOT NULL),
    CONSTRAINT idx_fiscal_documents_filename CHECK (filename IS NOT NULL)
);

-- Extracted data from XML documents (simplified structure)
CREATE TABLE extracted_data (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID REFERENCES fiscal_documents(id) ON DELETE CASCADE,
    
    -- Emitente (Supplier) data
    emitente JSONB NOT NULL,
    
    -- Destinatario (Customer) data  
    destinatario JSONB NOT NULL,
    
    -- Financial summary
    valor_total DECIMAL(15,2) NOT NULL,
    total_impostos DECIMAL(15,2) DEFAULT 0,
    data_emissao DATE NOT NULL,
    numero_nota VARCHAR(100),
    chave_acesso VARCHAR(44),
    
    created_at TIMESTAMP DEFAULT NOW(),
    
    -- Unique constraint to prevent duplicate extractions
    CONSTRAINT unique_document_extraction UNIQUE (document_id)
);

-- Document items (products/services from XML)
CREATE TABLE document_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id UUID REFERENCES fiscal_documents(id) ON DELETE CASCADE,
    
    -- Item details
    descricao TEXT NOT NULL,
    quantidade DECIMAL(10,3) DEFAULT 1,
    valor_unitario DECIMAL(15,2) NOT NULL,
    valor_total DECIMAL(15,2) NOT NULL,
    
    -- AI Categorization
    categoria VARCHAR(100),
    categoria_confianca DECIMAL(3,2) CHECK (categoria_confianca >= 0 AND categoria_confianca <= 1),
    
    -- Brazilian fiscal codes
    ncm VARCHAR(10),
    cfop VARCHAR(4),
    
    created_at TIMESTAMP DEFAULT NOW(),
    
    -- Performance indexes
    CONSTRAINT check_positive_values CHECK (
        quantidade > 0 AND valor_unitario >= 0 AND valor_total >= 0
    )
);

-- Executive reports generated by the system
CREATE TABLE executive_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    period_start DATE,
    period_end DATE,
    generated_at TIMESTAMP DEFAULT NOW(),
    
    -- Report metadata
    report_type VARCHAR(50) DEFAULT 'executive_summary' CHECK (
        report_type IN ('executive_summary', 'financial_analysis', 'supplier_analysis', 'product_analysis')
    ),
    
    -- Performance tracking
    generation_time_ms INTEGER CHECK (generation_time_ms >= 0),
    
    created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance optimization
CREATE INDEX idx_fiscal_documents_status ON fiscal_documents(status);
CREATE INDEX idx_fiscal_documents_uploaded_at ON fiscal_documents(uploaded_at);
CREATE INDEX idx_fiscal_documents_filename ON fiscal_documents(filename);

CREATE INDEX idx_extracted_data_document_id ON extracted_data(document_id);
CREATE INDEX idx_extracted_data_data_emissao ON extracted_data(data_emissao);
CREATE INDEX idx_extracted_data_valor_total ON extracted_data(valor_total);
CREATE INDEX idx_extracted_data_chave_acesso ON extracted_data(chave_acesso);

CREATE INDEX idx_document_items_document_id ON document_items(document_id);
CREATE INDEX idx_document_items_categoria ON document_items(categoria);
CREATE INDEX idx_document_items_valor_total ON document_items(valor_total);
CREATE INDEX idx_document_items_descricao_text ON document_items USING gin(to_tsvector('portuguese', descricao));

CREATE INDEX idx_executive_reports_generated_at ON executive_reports(generated_at);
CREATE INDEX idx_executive_reports_period ON executive_reports(period_start, period_end);
CREATE INDEX idx_executive_reports_type ON executive_reports(report_type);

-- Add comments for documentation
COMMENT ON TABLE fiscal_documents IS 'Main table for tracking uploaded XML fiscal documents and processing status';
COMMENT ON TABLE extracted_data IS 'Structured data extracted from XML documents with emitente/destinatario as JSONB';
COMMENT ON TABLE document_items IS 'Individual items (products/services) from fiscal documents with AI categorization';
COMMENT ON TABLE executive_reports IS 'Generated executive reports in PDF format with metadata';

COMMENT ON COLUMN extracted_data.emitente IS 'JSONB containing supplier data: {cnpj, razao_social, endereco, etc}';
COMMENT ON COLUMN extracted_data.destinatario IS 'JSONB containing customer data: {cnpj, razao_social, endereco, etc}';
COMMENT ON COLUMN document_items.categoria_confianca IS 'AI categorization confidence score from 0.0 to 1.0';